server:
  port: 9090

spring:
  application:
    name: SpringBootMybatisDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/uid-gen?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    hikari:
      username: root
      password: mysql
      minimum-idle: 0
      maximum-pool-size: 200
      max-lifetime: 36000
      connection-timeout: 36000
      idle-timeout: 1800

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.springbootmybatis.domain

logging:
   level:
     root: info
